# Generated by Django 6.1.1 on 2026-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
                ('hero_image_url', models.URLField(blank=True)),
                ('topbar_message', models.CharField(blank=True, max_length=200)),
                ('topbar_is_active', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_address', models.CharField(blank=True, max_length=300)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_telegram', models.URLField(blank=True)),
                ('social_whatsapp', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('promo_message', models.CharField(blank=True, max_length=200)),
                ('promo_is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'site content',
                'verbose_name_plural': 'site content',
            },
        ),
    ]
