# Generated by Django 6.1.1 on 2026-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('cover_image_url', models.CharField(blank=True, max_length=500)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='video_embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='video_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='video_poster_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
