# Generated by Django 6.1.1 on 2026-09-24 15:16

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_blogpost_sitecontent_video_embed_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=content.models.media_asset_upload_path)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
