# Generated by Django 6.1.1 on 2026-09-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_enabled', models.BooleanField(default=True, help_text='If off, shipping_cost is always 0 regardless of the flat rate below.')),
                ('shipping_flat_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order subtotal at/above which shipping is free. Blank/null disables the threshold (flat cost always applies).', max_digits=12, null=True)),
                ('guest_checkout_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When on, the public storefront should show a maintenance notice (frontend-enforced).')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('notify_new_order', models.BooleanField(default=True)),
                ('notify_low_stock', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'store settings',
                'verbose_name_plural': 'store settings',
            },
        ),
    ]
